/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WerewolfIndexImport } from './routes/werewolf/index'
import { Route as WerewolfIdImport } from './routes/werewolf/$id'
import { Route as WerewolfRulesIndexImport } from './routes/werewolf/rules/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WerewolfIndexRoute = WerewolfIndexImport.update({
  id: '/werewolf/',
  path: '/werewolf/',
  getParentRoute: () => rootRoute,
} as any)

const WerewolfIdRoute = WerewolfIdImport.update({
  id: '/werewolf/$id',
  path: '/werewolf/$id',
  getParentRoute: () => rootRoute,
} as any)

const WerewolfRulesIndexRoute = WerewolfRulesIndexImport.update({
  id: '/werewolf/rules/',
  path: '/werewolf/rules/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/werewolf/$id': {
      id: '/werewolf/$id'
      path: '/werewolf/$id'
      fullPath: '/werewolf/$id'
      preLoaderRoute: typeof WerewolfIdImport
      parentRoute: typeof rootRoute
    }
    '/werewolf/': {
      id: '/werewolf/'
      path: '/werewolf'
      fullPath: '/werewolf'
      preLoaderRoute: typeof WerewolfIndexImport
      parentRoute: typeof rootRoute
    }
    '/werewolf/rules/': {
      id: '/werewolf/rules/'
      path: '/werewolf/rules'
      fullPath: '/werewolf/rules'
      preLoaderRoute: typeof WerewolfRulesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/werewolf/$id': typeof WerewolfIdRoute
  '/werewolf': typeof WerewolfIndexRoute
  '/werewolf/rules': typeof WerewolfRulesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/werewolf/$id': typeof WerewolfIdRoute
  '/werewolf': typeof WerewolfIndexRoute
  '/werewolf/rules': typeof WerewolfRulesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/werewolf/$id': typeof WerewolfIdRoute
  '/werewolf/': typeof WerewolfIndexRoute
  '/werewolf/rules/': typeof WerewolfRulesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/werewolf/$id' | '/werewolf' | '/werewolf/rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/werewolf/$id' | '/werewolf' | '/werewolf/rules'
  id: '__root__' | '/' | '/werewolf/$id' | '/werewolf/' | '/werewolf/rules/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WerewolfIdRoute: typeof WerewolfIdRoute
  WerewolfIndexRoute: typeof WerewolfIndexRoute
  WerewolfRulesIndexRoute: typeof WerewolfRulesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WerewolfIdRoute: WerewolfIdRoute,
  WerewolfIndexRoute: WerewolfIndexRoute,
  WerewolfRulesIndexRoute: WerewolfRulesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/werewolf/$id",
        "/werewolf/",
        "/werewolf/rules/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/werewolf/$id": {
      "filePath": "werewolf/$id.tsx"
    },
    "/werewolf/": {
      "filePath": "werewolf/index.tsx"
    },
    "/werewolf/rules/": {
      "filePath": "werewolf/rules/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
